fix(alertmanager): pin patched grpc (#1122)

diff --git a/images/alertmanager/melange.yaml b/images/alertmanager/melange.yaml
--- a/images/alertmanager/melange.yaml
+++ b/images/alertmanager/melange.yaml
@@ -1,13 +1,14 @@
 package:
   name: prometheus-alertmanager
   version: "0.34.0"
-  epoch: 3
+  epoch: 4  # gRPC security floor
   description: Prometheus Alertmanager
   copyright:
     - license: Apache-2.0
 
 vars:
   source-commit: 085f0ef7eb41da24cab8cd000f1345b6250f2edb
+  grpc-floor: v1.83.2  # renovate: datasource=go depName=google.golang.org/grpc
 
 environment:
   contents:
@@ -41,12 +42,41 @@ pipeline:
       modroot: .
       packages: './cmd/alertmanager ./cmd/amtool'
   - runs: |
+      current="$(GOTOOLCHAIN=local go list -m -f '{{.Version}}' google.golang.org/grpc)"
+      if awk -v have="$current" -v want=${{vars.grpc-floor}} 'BEGIN {
+        split(substr(have, 2), h, /[.+-]/)
+        split(substr(want, 2), w, ".")
+        for (i = 1; i <= 3; i++) {
+          if (h[i] + 0 != w[i] + 0) exit (h[i] + 0 < w[i] + 0) ? 0 : 1
+        }
+        exit (have ~ /-/) ? 0 : 1
+      }'; then
+        GOTOOLCHAIN=local go get google.golang.org/grpc@${{vars.grpc-floor}}
+      fi
+  - runs: |
       flags="-s -w -X github.com/prometheus/common/version.Version=${{package.version}}"
       flags="$flags -X github.com/prometheus/common/version.Revision=${{vars.source-commit}}"
       go build -mod=readonly -trimpath -ldflags "$flags" -o alertmanager ./cmd/alertmanager
       go build -mod=readonly -trimpath -ldflags "$flags" -o amtool ./cmd/amtool
       install -m755 -D alertmanager "${{targets.destdir}}/usr/bin/alertmanager"
       install -m755 -D amtool "${{targets.destdir}}/usr/bin/amtool"
+      actual="$(go version -m "${{targets.destdir}}/usr/bin/alertmanager" \
+        | awk '$1 == "dep" && $2 == "google.golang.org/grpc" { print $3 }')"
+      [ -n "$actual" ] || {
+        echo "google.golang.org/grpc is not linked into alertmanager" >&2
+        exit 1
+      }
+      awk -v have="$actual" -v want=${{vars.grpc-floor}} 'BEGIN {
+        split(substr(have, 2), h, /[.+-]/)
+        split(substr(want, 2), w, ".")
+        for (i = 1; i <= 3; i++) {
+          if (h[i] + 0 != w[i] + 0) exit (h[i] + 0 > w[i] + 0) ? 0 : 1
+        }
+        exit (have ~ /-/) ? 1 : 0
+      }' || {
+        echo "google.golang.org/grpc version $actual is below required floor ${{vars.grpc-floor}}" >&2
+        exit 1
+      }
 
 test:
   pipeline:
